### ISSUE TITLE
Issue with testing

### ISSUE THREAD

**Issue by ShenZheng2000** [ykdai/BracketFlare#2]
Hi, I run the pretrained model for testing, and find the following error. I believe the function to_tensor() is in the wrong place. Could you please fix it? Thanks!

![image](https://github.com/ykdai/BracketFlare/assets/69662345/a1836e22-e852-4b13-8a19-31f03399c7be)

Follow-up: 

I successfully executed the pretrained model for testing purposes by modifying the inference() function as follows:

```
def inference(input_path, output_path, model_path):
    rot_transform = Compose([
        RandomGammaCorrection(10.0),
        RandomHorizontalFlip(1.0),
        RandomVerticalFlip(1.0)
    ])
    to_tensor = transforms.ToTensor()
    resize = transforms.Resize(512)
    crop =transforms.CenterCrop(512)
    gamma = torch.Tensor([2.2])

    model = MPRNet(img_ch=6, output_ch=6).cuda()
    model.load_state_dict(torch.load(model_path)['params'])
    model.eval()

    input_name_list = os.listdir(input_path)

    os.makedirs(os.path.join(output_path, "input"), exist_ok=True)
    os.makedirs(os.path.join(output_path, "deflare"), exist_ok=True)
    os.makedirs(os.path.join(output_path, "flare"), exist_ok=True)

    for cur_input_name in tqdm((input_name_list)):
        torch.cuda.empty_cache()

        cur_input_path = os.path.join(input_path, cur_input_name)
        cur_input_save_path = os.path.join(output_path, "input", cur_input_name)
        cur_deflare_path = os.path.join(output_path, "deflare", cur_input_name)
        cur_flare_path = os.path.join(output_path, "flare", cur_input_name)

        cur_input_img = Image.open(cur_input_path).convert("RGB")
        # cur_input_img = crop(resize(to_tensor(cur_input_img)))
        # cur_input_img = cur_input_img.cuda().unsqueeze(0)
        # NOTE: change to tensor later
        cur_input_img = crop(resize(cur_input_img))
        cur_input_ts = to_tensor(cur_input_img).cuda().unsqueeze(0)

        with torch.no_grad():
            lq_rot = rot_transform(cur_input_img)
            # lq = torch.concat((cur_input_img, lq_rot),1)
            # NOTE: concat with tensor
            lq_ts = to_tensor(lq_rot).cuda().unsqueeze(0)
            lq = torch.cat((cur_input_ts, lq_ts),1)
            output_img = model(lq)[0]

            deflare_img, flare_img_predicted, merge_img_predicted = predict_flare_from_6_channel(output_img, gamma)

            # torchvision.utils.save_image(cur_input_img, cur_input_save_path)
            # NOTE: save with torch tensor
            torchvision.utils.save_image(cur_input_ts, cur_input_save_path)
            torchvision.utils.save_image(flare_img_predicted, cur_flare_path)
            torchvision.utils.save_image(deflare_img, cur_deflare_path)
```

Is the inference code correct? If so, why is the experiment result on BDD night images showing poor performance with barely any flare removal? (left: input. right: deflared)

![image](https://github.com/ykdai/BracketFlare/assets/69662345/aee90fba-588e-46f7-97e2-37c857c3feb6)

**Comment by ykdai** [comment]
Thank your for your issues. I have checked the code and found that there is no problem for inference. Both transforms.Resize and transforms. CenterCrop can support both PIL img and tensor in the latest version. However, if you use the pytorch with version before v1.6, this error may occur. You can change to use the lastest torch and torchvision to avoid it.  

Besides, this project is mainly for the reflective flare removal. Therefore, our method does not aim to remove the scattering flares in the BDD night images. 

Also, for some videos captured by the smartphones, the anti-shake module may break our proposed prior. Thus, if you want to apply our algorithm to the video, be sure to use the original videos without the anti-shake algorithms.

**Comment by ShenZheng2000** [comment]
Thanks so much!
