### ISSUE TITLE
Verification issues during training

### ISSUE THREAD

**Issue by 1225743219** [ykdai/BracketFlare#4]
@DATASET_REGISTRY.register()
class ImageMask_Pair_Loader(Image_Pair_Loader):
	def __init__(self, opt):

		Image_Pair_Loader.__init__(self,opt)
		self.opt = opt
		self.gt_folder, self.lq_folder,self.mask_folder = opt['dataroot_gt'], opt['dataroot_lq'], opt['dataroot_mask']
		self.paths = glod_from_folder([self.lq_folder, self.gt_folder,self.mask_folder], ['lq', 'gt','mask'])
		print(f"self.paths!!!!!!!!!!!!!!!!!!!!!!!{len(self.paths)}!!")
		self.to_tensor=transforms.ToTensor()
		self.gt_size=opt['gt_size']
		self.transform = transforms.Compose([transforms.Resize(self.gt_size), transforms.CenterCrop(self.gt_size), transforms.ToTensor()])

	def __getitem__(self, index):
		gt_path = self.paths['gt'][index]
		lq_path = self.paths['lq'][index]
		print(f"{gt_path}+{index}")
		mask_path = self.paths['mask'][index]
		img_lq=self.transform(Image.open(lq_path).convert('RGB'))
		img_gt=self.transform(Image.open(gt_path).convert('RGB'))
		img_mask = self.transform(Image.open(mask_path).convert('RGB'))

		return {'lq': img_lq, 'gt': img_gt,'mask':img_mask}

	def __len__(self):
		return len(self.paths)    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!   len(self.paths) return just 3!!!  we need return 40
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ykdai** [comment]
We feel so sorry for that! It will definetely influence the logging result, I have fixed it in our local repository but forget to update it. You can change the __len__ fucntion to return len(self.paths['lq']) to fix this problem. I have updated the code. Thank you so much for your feedback.
