### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by FireWallDragonDarkFluid** [ykdai/BracketFlare#5]
Hi!

Thanks for your work. I use your code to train the work, however, the validation results do not
get any better compare to the very first output results of the training loop after one-day training. 
It seems that there might be some problems in your code. 

Would you mind using the repo to retrain the work to verify this? Thanks a lot.

**Comment by ykdai** [comment]
I noticed you closed the issue. Have you fixed the problem?

**Comment by FireWallDragonDarkFluid** [comment]
Thanks for your kind reply.

I am now retraining the repo, the results do get better but haven't reach the performance reported from the paper.
Most likely, the problem occurred  due to my lack of training time. So, I decided to close the issue and retrain it a bit more.
